[tool.poetry]
name = "Powerloom Snapshotter"
version = "0.1.0"
description = ""
authors = ["Powerloom, Inc."]
license = "Apache-2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
redis = "^4.6.0"
timeago = "^1.0.16"
typer = "^0.12.3"
psutil = "^5.9.5"
importlib = "^1.0.4"
pika = "^1.3.2"
gunicorn = "^20.1.0"
aiohttp = "^3.8.5"
web3 = "^7"
tenacity = "^9.1.2"
limits = "^2.8.0"
uvicorn = "^0.20.0"
frozendict = "^2.3.8"
multiaddr = "^0.0.9"
idna = "^3.4"
uvloop = "^0.19.0"
loguru = "^0.7.0"
httpx = "^0.27.1"
ifps-client = {git = "https://git@github.com/PowerLoom/py-ipfs-client.git", rev = "a61061464faf56b8fa34d0e5f3d71fe58d14ac53"}
rpc_helper = {git = "https://git@github.com/PowerLoom/rpc-helper.git", branch = "develop"}
aiorwlock = "^1.3.0"
fastapi-pagination = "^0.12.12"
coincurve = "^19.0.1"
grpclib = {extras = ["protobuf"], version = "^0.4.7"}
grpcio-tools = "^1.62.1"
aiolimiter = "^1.1.0"
aioboto3 = "^14.1.0"
dramatiq = "^1.17.1"
fastapi = "^0.115.12"
pydantic = "^2.11.3"
gql = "^3.5.3"
jinja2 = "^3.1.6"
python-dotenv = "^1.1.0"
pytest = "^8.4.0"
certifi = "^2025.4.26"
async-lru = "^2.0.5"
[tool.poetry.group.dev.dependencies]
pytest-cov = "^5.0.0"
pytest-asyncio = "^0.24.0"
fakeredis = "^2.25.1"
pytest-mock = "^3.14.0"
pympp = {version = "0.4.0", extras = ["tempo"]}

# Add pytest configuration section
[tool.pytest.ini_options]
# testpaths = ["tests"]
asyncio_mode = "auto"
markers = [
    "ipfs: marks tests that require a running IPFS daemon"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
